// Generated by CoffeeScript 1.9.2
var Mesh, config, mesh;

Mesh = require('freebase-mesh');

config = require('./config');

module.exports.mesh = mesh = Mesh();

mesh.initialize(config, function(err) {
  if (err != null) {
    console.log(err);
    return process.exit(1);
  }
});
