// Generated by CoffeeScript 1.9.2
module.exports.init = function(arg, callback) {
  var app, express, host, port, server;
  port = arg.port, host = arg.host;
  express = require('express');
  app = express();
  app.get('/', function(req, res) {
    return res.sendStatus(200);
  });
  return server = app.listen(port, host, function() {
    return callback(null, {
      startServer: function(callback) {
        console.log('start');
        return server = app.listen(port, host, function() {
          return callback(null, 'started');
        });
      },
      stopServer: function(callback) {
        console.log('stop');
        return server.close(function() {
          return callback(null, 'stopped');
        });
      }
    });
  });
};
