// Generated by CoffeeScript 1.9.2
module.exports.init = function(arg, callback) {
  var app, express, host, port, server;
  port = arg.port, host = arg.host;
  express = require('express');
  app = express();
  app.get('/', function(req, res) {
    return res.sendStatus(200);
  });
  return server = app.listen(port, host, function() {
    var running;
    running = true;
    return callback(null, {
      startServer: function(callback) {
        if (running) {
          return callback(null, 'Already running');
        }
        console.log('start', new Date);
        return server = app.listen(port, host, function() {
          running = true;
          return callback(null, 'STARTED web server at http://mesh.snowball.global');
        });
      },
      stopServer: function(callback) {
        if (!running) {
          return callback(null, 'Already stopped');
        }
        console.log('stop', new Date);
        return server.close(function() {
          running = false;
          return callback(null, 'STOPPED web server at http://mesh.snowball.global');
        });
      }
    });
  });
};
